title: Rusheb's Blog
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Rusheb. I'm not sure what I will blog about yet.
github_username: rusheb

# Build settings
theme: minima
plugins:
  - jekyll-feed
